name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Remove existing tailwind symlink
        run: |
          rm -f /home/runner/work/pyevents.github.io/pyevents.github.io/node_modules/.bin/tailwind

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          python -m pip install --upgrade pip
          pip install pelican markdown ghp-import

      - name: Build Tailwind CSS
        run: |
          npm run build:css

      - name: Build the site
        run: |
          pelican content -s publishconf.py --output output

      - name: Fix permissions
        run: |
          chmod -c -R +rX output | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
